let V=[],L=[],F=[],S=[],R=[],blob=null,processedBlob=null,rotation=0,enhanced=false,$=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),rup=n=>new Intl.NumberFormat('id-ID').format(Math.round(n||0));
async function init(){F=await all('fuelTypes');if(!F.length){for(let n of ['Pertalite','Pertamax','Pertamax Green 95','Pertamax Turbo','Revvo 92','Revvo 95','BP 92','BP Ultimate'])await put('fuelTypes',{id:uid(),name:n});F=await all('fuelTypes')}V=await all('vehicles');L=await all('fuelLogs');S=await all('stations');R=await all('receiptImages');render();$('date').value=today()}
function opts(id,a,text){$(id).innerHTML=a.map(x=>`<option value="${x.id}">${x[text]}</option>`).join('')}
function render(){opts('fuelType',F,'name');opts('of',F,'name');opts('vfuel',F,'name');opts('vehicleId',V,'plateNumber');opts('ovh',V,'plateNumber');let m=today().slice(0,7),x=L.filter(q=>q.transactionDate?.startsWith(m)),lit=x.reduce((a,q)=>a+q.volume,0),cost=x.reduce((a,q)=>a+q.totalAmount,0),km=x.filter(q=>q.kmPerLiter).map(q=>q.kmPerLiter);$('stats').innerHTML=[['BBM bulan',lit.toFixed(2)+' L'],['Biaya','Rp '+rup(cost)],['Transaksi',x.length],['Rata-rata',km.length?(km.reduce((a,b)=>a+b,0)/km.length).toFixed(2)+' km/L':'—']].map(q=>`<div class="stat"><small>${q[0]}</small><b>${q[1]}</b></div>`).join('');let q=($('search').value||'').toLowerCase();$('list').innerHTML=L.filter(x=>[x.stationName,x.fuelTypeName,x.vehiclePlate].join(' ').toLowerCase().includes(q)).sort((a,b)=>(b.transactionDate+b.transactionTime).localeCompare(a.transactionDate+a.transactionTime)).map(x=>`<div class="item"><b>${x.stationName}</b> · ${x.fuelTypeName}<br>${x.volume} L · Rp ${rup(x.totalAmount)} · Odo ${x.odometer}<br><small>${x.transactionDate} ${x.transactionTime||''} · ${x.kmPerLiter?x.kmPerLiter.toFixed(2)+' km/L':'km/L —'} · ${x.inputMethod}${x.ocrConfidence!=null?' · OCR '+x.ocrConfidence+'%':''}</small><br><button onclick="edit('${x.id}')">Edit</button><button onclick="removeLog('${x.id}')">Hapus</button></div>`).join('')||'<p>Belum ada transaksi.</p>';renderArchive()}
async function renderArchive(){R=await all('receiptImages');const items=R.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));if(!items.length){$('receiptArchive').innerHTML='';return}let html='<h3>Arsip Struk</h3>';for(const r of items){const url=URL.createObjectURL(r.blob);html+=`<div class="item"><img class="receipt-thumb" src="${url}" alt="Struk"> <b>${r.fileName||'Struk'}</b><br><small>${new Date(r.createdAt).toLocaleString('id-ID')} · ${r.hash?'SHA-256 tersimpan':''}</small></div>`;setTimeout(()=>URL.revokeObjectURL(url),30000)}$('receiptArchive').innerHTML=html}
function prev(v,id,odo){return L.filter(x=>x.vehicleId===v&&x.id!==id&&x.odometer<odo).sort((a,b)=>b.odometer-a.odometer)[0]||null}
async function save(x){if(!V.length)throw Error('Buat profil kendaraan terlebih dahulu');let p=prev(x.vehicleId,x.id,x.odometer),e=valid(x,p);if(e.length)throw Error(e.join(', '));let st=S.find(q=>q.stationName.toLowerCase()===x.stationName.toLowerCase()),isNew=!st;if(!st)st={id:uid(),stationName:x.stationName,location:'',brand:'',transactionCount:0,lastTransaction:null,createdAt:now(),updatedAt:now()};if(isNew)st.transactionCount=0;st.transactionCount=(st.transactionCount||0)+(x._isNew?1:0);st.lastTransaction=x.transactionDate+'T'+(x.transactionTime||'00:00');st.updatedAt=now();await put('stations',st);x.stationId=st.id;delete x._isNew;Object.assign(x,derived(x,p));await put('fuelLogs',x);S=await all('stations');L=recomputeAll(await all('fuelLogs'));for(const row of L)await put('fuelLogs',row);render()}
$('fuelForm').onsubmit=async e=>{e.preventDefault();let id=$('editId').value,v=V.find(x=>x.id===$('vehicleId').value),f=F.find(x=>x.id===$('fuelType').value),x={id:id||uid(),vehicleId:v.id,stationName:$('station').value.trim(),transactionDate:$('date').value,transactionTime:$('time').value,fuelTypeId:f.id,fuelTypeName:f.name,volume:+$('volume').value,pricePerLiter:+$('price').value,totalAmount:+$('total').value,vehiclePlate:$('plate').value||v.plateNumber,odometer:+$('odo').value,isFullTank:$('fullTank').checked,inputMethod:'MANUAL',notes:$('notes').value,createdAt:id?(L.find(q=>q.id===id)?.createdAt||now()):now(),updatedAt:now(),_isNew:!id};try{await save(x);e.target.reset();$('editId').value='';$('date').value=today();$('cancel').hidden=true;$('error').textContent=''}catch(z){$('error').textContent=z.message}};
window.edit=async id=>{let x=L.find(q=>q.id===id);$('editId').value=x.id;$('vehicleId').value=x.vehicleId;$('station').value=x.stationName;$('date').value=x.transactionDate;$('time').value=x.transactionTime;$('fuelType').value=x.fuelTypeId;$('volume').value=x.volume;$('price').value=x.pricePerLiter;$('total').value=x.totalAmount;$('plate').value=x.vehiclePlate;$('odo').value=x.odometer;$('fullTank').checked=x.isFullTank;$('notes').value=x.notes||'';$('cancel').hidden=false;activate('log')};
window.removeLog=async id=>{if(confirm('Hapus transaksi ini?')){await del('fuelLogs',id);L=recomputeAll(await all('fuelLogs'));for(const row of L)await put('fuelLogs',row);render()}};
$('cancel').onclick=()=>location.reload();$('search').oninput=render;$('vehicleForm').onsubmit=async e=>{e.preventDefault();let x={id:V[0]?.id||uid(),brand:$('brand').value,model:$('model').value,year:+$('year').value,plateNumber:$('vplate').value.toUpperCase(),tankCapacity:+$('tank').value,fuelTypeId:$('vfuel').value,initialOdometer:+$('initial').value,createdAt:V[0]?.createdAt||now(),updatedAt:now()};await put('vehicles',x);V=await all('vehicles');$('vm').textContent='Tersimpan';render()};
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function csvCell(v){const s=String(v??'');return '"'+s.replace(/"/g,'""')+'"'}
$('exportCsv').onclick=()=>{const head=['date','time','vehicle','SPBU','fuelType','volume','pricePerLiter','totalAmount','plate','odometer','distance','kmPerLiter','costPerKm','fullTank','inputMethod','ocrConfidence','notes'];const rows=L.map(x=>{const v=V.find(q=>q.id===x.vehicleId);return [x.transactionDate,x.transactionTime,v?.plateNumber||'',x.stationName,x.fuelTypeName,x.volume,x.pricePerLiter,x.totalAmount,x.vehiclePlate,x.odometer,x.distance,x.kmPerLiter,x.costPerKm,x.isFullTank,x.inputMethod,x.ocrConfidence??'',x.notes]});download('fuel-log.csv',[head,...rows].map(r=>r.map(csvCell).join(',')).join('\n'),'text/csv;charset=utf-8')};$('exportJson').onclick=()=>download('fuel-log-backup.json',JSON.stringify({schemaVersion:2,exportedAt:now(),vehicles:V,fuelLogs:L,fuelTypes:F,stations:S,receiptImages:R.map(x=>({...x,blob:undefined}))},null,2),'application/json');
function activate(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-tab="${id}"]`).classList.add('active')}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>activate(b.dataset.tab));
async function sha256(file){const buf=await file.arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',buf);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function previewFile(file){blob=file;processedBlob=file;rotation=0;enhanced=false;$('preview').src=URL.createObjectURL(file);$('previewWrap').hidden=false;$('ocr').disabled=false;$('ocrStatus').textContent='Struk siap diproses.'}
$('receipt').onchange=e=>{if(e.target.files[0])previewFile(e.target.files[0])};
async function canvasBlob(file){const img=new Image();img.src=URL.createObjectURL(file);await img.decode();let c=document.createElement('canvas'),ctx=c.getContext('2d'),angle=((rotation%360)+360)%360;if(angle===90||angle===270){c.width=img.height;c.height=img.width}else{c.width=img.width;c.height=img.height}ctx.translate(c.width/2,c.height/2);ctx.rotate(angle*Math.PI/180);ctx.filter=enhanced?'grayscale(1) contrast(1.45) brightness(1.08)':'grayscale(1)';ctx.drawImage(img,-img.width/2,-img.height/2);URL.revokeObjectURL(img.src);return await new Promise(res=>c.toBlob(res,'image/jpeg',.92))}
$('rotate').onclick=async()=>{if(!blob)return;rotation=(rotation+90)%360;processedBlob=await canvasBlob(blob);$('preview').src=URL.createObjectURL(processedBlob)};$('enhance').onclick=async()=>{if(!blob)return;enhanced=!enhanced;processedBlob=await canvasBlob(blob);$('preview').src=URL.createObjectURL(processedBlob);$('ocrStatus').textContent=enhanced?'Kontras ditingkatkan.':'Peningkatan kontras dimatikan.'};
$('ocr').onclick=async()=>{if(!blob)return;$('raw').textContent='OCR berjalan…';$('ocrStatus').textContent='Memproses gambar dan membaca teks…';try{processedBlob=processedBlob||blob;let r=await Tesseract.recognize(processedBlob,'eng',{logger:m=>{if(m.status&&m.progress!=null)$('ocrStatus').textContent=`${m.status} ${Math.round(m.progress*100)}%`}});$('raw').textContent=r.data.text;let x=parseReceipt(r.data.text);x.tesseractConfidence=Math.round(r.data.confidence||0);x.dataConfidence=x.confidence;x.confidence=Math.round((x.dataConfidence+x.tesseractConfidence)/2);$('ocrConfidence').hidden=false;$('ocrConfidence').textContent=`Confidence OCR: ${x.tesseractConfidence}% · Confidence data: ${x.dataConfidence}% · Gabungan: ${x.confidence}%`;$('os').value=x.stationName;$('od').value=x.transactionDate||today();$('ot').value=x.transactionTime;$('ov').value=x.volume||'';$('op').value=x.pricePerLiter||'';$('oa').value=x.totalAmount||'';$('opl').value=x.vehiclePlate||'';$('ocrWarnings').innerHTML=validateReceiptData(x).map(e=>`<div class="warning">${e}</div>`).join('')||'<div class="ok">Data utama terdeteksi. Tetap periksa sebelum simpan.</div>';$('ocrForm').hidden=false;if(x.fuelTypeName){let f=F.find(q=>q.name.toUpperCase()===x.fuelTypeName.toUpperCase());if(f)$('of').value=f.id} }catch(e){$('raw').textContent='OCR gagal: '+e.message;$('ocrStatus').textContent='OCR gagal.'}};
$('ocrForm').onsubmit=async e=>{e.preventDefault();if(!V.length){$('ow').textContent='Buat profil kendaraan terlebih dahulu.';return}let v=V.find(x=>x.id===$('ovh').value),f=F.find(x=>x.id===$('of').value),x={id:uid(),vehicleId:v.id,stationName:$('os').value.trim(),transactionDate:$('od').value,transactionTime:$('ot').value,fuelTypeId:f.id,fuelTypeName:f.name,volume:+$('ov').value,pricePerLiter:+$('op').value,totalAmount:+$('oa').value,vehiclePlate:$('opl').value||v.plateNumber,odometer:+$('oo').value,isFullTank:false,inputMethod:'OCR',ocrConfidence:+($('ocrConfidence').textContent.match(/Confidence OCR:\s*(\d+)/)?.[1]||0),ocrDataConfidence:+($('ocrConfidence').textContent.match(/Confidence data:\s*(\d+)/)?.[1]||0),ocrCombinedConfidence:+($('ocrConfidence').textContent.match(/Gabungan:\s*(\d+)/)?.[1]||0),createdAt:now(),updatedAt:now(),_isNew:true};try{const hash=await sha256(blob),dupe=R.find(r=>r.hash===hash);if(dupe)throw Error('Struk ini sudah pernah disimpan (duplikat terdeteksi).');await save(x);await put('receiptImages',{id:uid(),fuelLogId:x.id,blob,mimeType:blob.type,hash,fileName:blob.name||'receipt.jpg',rotation,enhanced,createdAt:now()});R=await all('receiptImages');activate('history');render()}catch(z){$('ow').textContent=z.message}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');init();
